apiVersion: v1
kind: PersistentVolume 
metadata:
  name: scylla-0 # This is the persistent volume needs to be created well before. 
spec:
  capacity:
    storage: 500Mi # Change this to your desired limit based on your requirement
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scylla-ssd # Name of storage class created from scylla-storageclass.yaml
  local:
    path: /var/lib # Path should be present in nodes
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname # Can any annotations from nodes can be used but should able to identify the correct node.
          operator: In
          values: 
            - node-1 # Correct node id from kunbectl describe nodes
            
---
    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylla-1
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scylla-ssd
  local:
    path: /var/lib
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
            - node-2

---
    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylla-2
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scylla-ssd
  local:
    path: /var/lib
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
            - node-3