kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: scylla-ssd # Name of the storage class. Just make a note as this will be used across other yamls.
provisioner: kubernetes.io/no-provisioner # This is for local storage
volumeBindingMode: WaitForFirstConsumer 